#Requires -Version 5.1
<#
.SYNOPSIS
    Copilot Usage Monitor - One-time Setup

.DESCRIPTION
    PAT 1回の入力で Copilot 消費量モニターを環境構築します。
    生成ファイル:
      %USERPROFILE%\copilot_billing\gh_token.sec
      %USERPROFILE%\copilot_billing\config.json
      %USERPROFILE%\copilot_billing\Get-CopilotQuota.ps1
      %USERPROFILE%\.copilot\copilot-instructions.md

.PARAMETER Force
    既存ファイルを確認なしで上書きします。

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File Setup-CopilotMonitor.ps1
#>

[CmdletBinding()]
param([switch]$Force)

$ErrorActionPreference = "Stop"

$billingDir   = "$env:USERPROFILE\copilot_billing"
$copilotDir   = "$env:USERPROFILE\.copilot"
$tokenFile    = "$billingDir\gh_token.sec"
$configFile   = "$billingDir\config.json"
$quotaScript  = "$billingDir\Get-CopilotQuota.ps1"
$instructFile = "$copilotDir\copilot-instructions.md"

Write-Host ""
Write-Host "=== Copilot Usage Monitor Setup ===" -ForegroundColor Cyan

# ------------------------------------------------------------------
# 1. Prerequisites
# ------------------------------------------------------------------
Write-Host "`n[1] Checking prerequisites..." -ForegroundColor Cyan
$ghCmd = Get-Command "gh" -ErrorAction SilentlyContinue
if (-not $ghCmd) {
    Write-Host "[ERROR] GitHub CLI (gh) not found." -ForegroundColor Red
    Write-Host "        Install: https://cli.github.com/" -ForegroundColor Yellow
    exit 1
}
Write-Host "  [OK] GitHub CLI : $($ghCmd.Source)" -ForegroundColor Green
Write-Host "  [OK] PowerShell : $($PSVersionTable.PSVersion)" -ForegroundColor Green

# ------------------------------------------------------------------
# 2. PAT input
# ------------------------------------------------------------------
Write-Host "`n[2] GitHub PAT configuration" -ForegroundColor Cyan
$skipToken = $false
if ((Test-Path $tokenFile) -and (-not $Force)) {
    $ans = Read-Host "  Existing token found. Overwrite? [y/N]"
    if ($ans -notmatch "^[Yy]") {
        Write-Host "  [SKIP] Keeping existing token." -ForegroundColor Yellow
        $skipToken = $true
    }
}

$secPat = $null
if (-not $skipToken) {
    Write-Host "  Get PAT from: https://github.com/settings/tokens/new" -ForegroundColor DarkGray
    Write-Host "  Required scope: [copilot]  (or read:user)" -ForegroundColor DarkGray
    $secPat = Read-Host "  PAT (input hidden)" -AsSecureString

    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secPat)
    try {
        $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
        if ([string]::IsNullOrWhiteSpace($plain)) {
            Write-Host "[ERROR] PAT is empty. Aborting." -ForegroundColor Red
            exit 1
        }
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
        $plain = $null
    }
    Write-Host "  [OK] PAT received (not displayed)." -ForegroundColor Green
}

# ------------------------------------------------------------------
# 3. Proxy configuration
# ------------------------------------------------------------------
Write-Host "`n[3] Proxy configuration" -ForegroundColor Cyan
$defaultProxy = "http://in-proxy-o.denso.co.jp:8080"
$detectedProxy = ""
if ($env:HTTPS_PROXY) { $detectedProxy = $env:HTTPS_PROXY }
elseif ($env:HTTP_PROXY) { $detectedProxy = $env:HTTP_PROXY }

# 環境変数で検出できた場合はそれを使用、なければ社内デフォルト
$candidateProxy = if ($detectedProxy) { $detectedProxy } else { $defaultProxy }

Write-Host "  Default proxy: $candidateProxy" -ForegroundColor DarkGray
$ans = Read-Host "  このプロキシを使用しますか？変更する場合は新しいURLを入力、不要なら 'none' と入力 [Enter=使用]"

if ($ans -eq "none") {
    $proxyUrl = ""
    Write-Host "  [OK] No proxy (direct connection)" -ForegroundColor Green
} elseif ($ans -ne "") {
    $proxyUrl = $ans
    Write-Host "  [OK] Proxy: $proxyUrl" -ForegroundColor Green
} else {
    $proxyUrl = $candidateProxy
    Write-Host "  [OK] Proxy: $proxyUrl" -ForegroundColor Green
}

# ------------------------------------------------------------------
# 4. File generation
# ------------------------------------------------------------------
Write-Host "`n[4] Generating files..." -ForegroundColor Cyan

New-Item -ItemType Directory -Path $billingDir -Force | Out-Null
New-Item -ItemType Directory -Path $copilotDir  -Force | Out-Null

# Token (DPAPI encrypted)
if (-not $skipToken) {
    $secPat | ConvertFrom-SecureString | Set-Content $tokenFile -Encoding UTF8
    $secPat = $null
    Write-Host "  [OK] Token saved (DPAPI encrypted): $tokenFile" -ForegroundColor Green
}

# config.json
@{ proxy = $proxyUrl } | ConvertTo-Json | Set-Content $configFile -Encoding UTF8
Write-Host "  [OK] Config saved: $configFile" -ForegroundColor Green

# Get-CopilotQuota.ps1
$qScript = '#Requires -Version 5.1' + [Environment]::NewLine
$qScript += '# Auto-generated by Setup-CopilotMonitor.ps1' + [Environment]::NewLine
$qScript += '$ErrorActionPreference = "Stop"' + [Environment]::NewLine
$qScript += '$billingDir = "$env:USERPROFILE\copilot_billing"' + [Environment]::NewLine
$qScript += '$tokenFile  = "$billingDir\gh_token.sec"' + [Environment]::NewLine
$qScript += '$configFile = "$billingDir\config.json"' + [Environment]::NewLine
$qScript += 'if (-not (Test-Path $tokenFile)) { throw "Token file not found: $tokenFile  -> Re-run Setup-CopilotMonitor.ps1" }' + [Environment]::NewLine
$qScript += '$ghExe = "gh"' + [Environment]::NewLine
$qScript += 'foreach ($c in @("$env:ProgramFiles\GitHub CLI\gh.exe","$env:LOCALAPPDATA\Programs\GitHub CLI\gh.exe")) {' + [Environment]::NewLine
$qScript += '    if (Test-Path $c) { $ghExe = $c; break }' + [Environment]::NewLine
$qScript += '}' + [Environment]::NewLine
$qScript += '$ptr = [IntPtr]::Zero' + [Environment]::NewLine
$qScript += 'try {' + [Environment]::NewLine
$qScript += '    if (Test-Path $configFile) {' + [Environment]::NewLine
$qScript += '        $cfg = Get-Content $configFile -Raw | ConvertFrom-Json' + [Environment]::NewLine
$qScript += '        if ($cfg.proxy) { $env:HTTPS_PROXY = $cfg.proxy; $env:HTTP_PROXY = $cfg.proxy }' + [Environment]::NewLine
$qScript += '    }' + [Environment]::NewLine
$qScript += '    $secure = Get-Content $tokenFile | ConvertTo-SecureString' + [Environment]::NewLine
$qScript += '    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)' + [Environment]::NewLine
$qScript += '    $env:GH_TOKEN = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)' + [Environment]::NewLine
$qScript += '    $raw = & $ghExe api /copilot_internal/user' + [Environment]::NewLine
$qScript += '    $q = $raw | ConvertFrom-Json' + [Environment]::NewLine
$qScript += '    $p = $q.quota_snapshots.premium_interactions' + [Environment]::NewLine
$qScript += '    [PSCustomObject]@{' + [Environment]::NewLine
$qScript += '        timestamp_jst       = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")' + [Environment]::NewLine
$qScript += '        login               = $q.login' + [Environment]::NewLine
$qScript += '        quota_id            = $p.quota_id' + [Environment]::NewLine
$qScript += '        remaining           = [double]$p.quota_remaining' + [Environment]::NewLine
$qScript += '        percent_remaining   = [math]::Round([double]$p.percent_remaining, 1)' + [Environment]::NewLine
$qScript += '        entitlement         = [double]$p.entitlement' + [Environment]::NewLine
$qScript += '        used                = [double]($p.entitlement - $p.quota_remaining)' + [Environment]::NewLine
$qScript += '        overage_count       = [double]$p.overage_count' + [Environment]::NewLine
$qScript += '        overage_permitted   = [bool]$p.overage_permitted' + [Environment]::NewLine
$qScript += '        reset_date          = $q.quota_reset_date' + [Environment]::NewLine
$qScript += '        token_based_billing = [bool]$q.token_based_billing' + [Environment]::NewLine
$qScript += '    } | ConvertTo-Json -Depth 3' + [Environment]::NewLine
$qScript += '} finally {' + [Environment]::NewLine
$qScript += '    if ($ptr -ne [IntPtr]::Zero) { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr) }' + [Environment]::NewLine
$qScript += '    Remove-Item Env:GH_TOKEN    -ErrorAction SilentlyContinue' + [Environment]::NewLine
$qScript += '    Remove-Item Env:HTTPS_PROXY -ErrorAction SilentlyContinue' + [Environment]::NewLine
$qScript += '    Remove-Item Env:HTTP_PROXY  -ErrorAction SilentlyContinue' + [Environment]::NewLine
$qScript += '}'

Set-Content $quotaScript $qScript -Encoding UTF8
Write-Host "  [OK] Quota script  : $quotaScript" -ForegroundColor Green

# copilot-instructions.md
$md  = "# Copilot Chat Usage Monitor" + [Environment]::NewLine + [Environment]::NewLine
$md += "All responses must include the usage monitor section at the end." + [Environment]::NewLine + [Environment]::NewLine
$md += "## Command" + [Environment]::NewLine + [Environment]::NewLine
$md += "Run this PowerShell command and parse the JSON:" + [Environment]::NewLine + [Environment]::NewLine
$md += "powershell -NoProfile -ExecutionPolicy Bypass -File `"$quotaScript`"" + [Environment]::NewLine + [Environment]::NewLine
$md += "## Fields to read" + [Environment]::NewLine + [Environment]::NewLine
$md += "- remaining" + [Environment]::NewLine
$md += "- percent_remaining" + [Environment]::NewLine
$md += "- entitlement" + [Environment]::NewLine
$md += "- used" + [Environment]::NewLine
$md += "- reset_date" + [Environment]::NewLine
$md += "- timestamp_jst" + [Environment]::NewLine + [Environment]::NewLine
$md += "## Session start values" + [Environment]::NewLine + [Environment]::NewLine
$md += "On first response in each session, store:" + [Environment]::NewLine + [Environment]::NewLine
$md += "- start_remaining = remaining" + [Environment]::NewLine
$md += "- start_percent = percent_remaining" + [Environment]::NewLine
$md += "- start_time = timestamp_jst" + [Environment]::NewLine + [Environment]::NewLine
$md += "## Footer format" + [Environment]::NewLine + [Environment]::NewLine
$md += "---" + [Environment]::NewLine
$md += "📊 Usage Monitor" + [Environment]::NewLine
$md += "- Start : {start_remaining} ({start_percent}%) @ {start_time}" + [Environment]::NewLine
$md += "- Now   : {remaining} ({percent_remaining}%)" + [Environment]::NewLine
$md += "- Used  : {start_remaining - remaining} units" + [Environment]::NewLine
$md += "- Total : {entitlement} units" + [Environment]::NewLine
$md += "- Reset : {reset_date}" + [Environment]::NewLine + [Environment]::NewLine
$md += "## Rules" + [Environment]::NewLine + [Environment]::NewLine
$md += "- Always append this footer to every response, no exceptions." + [Environment]::NewLine
$md += "- Do NOT ask user for confirmation before running the command." + [Environment]::NewLine
$md += "- Do NOT display, save, or echo the PAT value." + [Environment]::NewLine
$md += "- Do NOT modify env vars HTTPS_PROXY / HTTP_PROXY / NO_PROXY / GH_TOKEN permanently." + [Environment]::NewLine
$md += "- On error, show: '📊 Usage Monitor (failed to retrieve)'" + [Environment]::NewLine

$writeInst = $true
if ((Test-Path $instructFile) -and (-not $Force)) {
    $ans = Read-Host "  copilot-instructions.md already exists. Overwrite? [Y/n]"
    if ($ans -match "^[Nn]") {
        Write-Host "  [SKIP] Keeping existing copilot-instructions.md" -ForegroundColor Yellow
        $writeInst = $false
    }
}
if ($writeInst) {
    Set-Content $instructFile $md -Encoding UTF8
    Write-Host "  [OK] Instructions  : $instructFile" -ForegroundColor Green
}

# ------------------------------------------------------------------
# 5. Verification
# ------------------------------------------------------------------
Write-Host "`n[5] Verifying..." -ForegroundColor Cyan
try {
    $result = powershell -NoProfile -ExecutionPolicy Bypass -File $quotaScript 2>&1
    $json   = $result | ConvertFrom-Json
    Write-Host "  [OK] Connected as  : $($json.login)" -ForegroundColor Green
    Write-Host "  [OK] Remaining     : $($json.remaining) / $($json.entitlement) ($($json.percent_remaining)%)" -ForegroundColor Green
    Write-Host "  [OK] Reset date    : $($json.reset_date)" -ForegroundColor Green
} catch {
    Write-Host "  [WARN] Verification failed: $_" -ForegroundColor Yellow
    Write-Host "  Check: PAT scope (copilot), expiry, proxy settings." -ForegroundColor Yellow
}

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
Write-Host ""
Write-Host "=== Setup Complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Yellow
Write-Host "    1. Restart VS Code to apply copilot-instructions.md"
Write-Host "    2. Open Copilot Chat - monitor will appear in every response"
Write-Host ""
Write-Host "  Generated files:"
Write-Host "    $tokenFile"
Write-Host "    $configFile"
Write-Host "    $quotaScript"
Write-Host "    $instructFile"
Write-Host ""
